# Generated by Django 6.0 on 2026-02-08 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_contactdb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactDb',
        ),
    ]
