# Generated by Django 6.0 on 2026-02-20 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0006_prebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prebook',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='prebook',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
