# Generated by Django 6.0 on 2026-02-21 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0007_alter_prebook_quantity_alter_prebook_total_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRegister',
        ),
        migrations.RenameField(
            model_name='contactdb',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contactdb',
            old_name='Message',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='contactdb',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='contactdb',
            old_name='Subject',
            new_name='subject',
        ),
    ]
