# Generated by Django 6.0 on 2026-02-25 15:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0012_alter_cart_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveCheckout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.EmailField(blank=True, max_length=100, null=True)),
                ('OrderType', models.CharField(default='Instant', max_length=50)),
                ('OrderDate', models.DateField(default=datetime.date.today)),
                ('OrderTime', models.TimeField(blank=True, null=True)),
                ('TotalAmount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('Status', models.CharField(default='Pending', max_length=20)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
