# Generated by Django 6.0.2 on 2026-02-28 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0013_savecheckout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savecheckout',
            old_name='CreatedAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='savecheckout',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='savecheckout',
            old_name='OrderDate',
            new_name='order_date',
        ),
        migrations.RenameField(
            model_name='savecheckout',
            old_name='OrderTime',
            new_name='order_time',
        ),
        migrations.RenameField(
            model_name='savecheckout',
            old_name='Status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='savecheckout',
            old_name='TotalAmount',
            new_name='total_amount',
        ),
        migrations.RenameField(
            model_name='savecheckout',
            old_name='Username',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.RemoveField(
            model_name='savecheckout',
            name='OrderType',
        ),
        migrations.AddField(
            model_name='order',
            name='checkout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='UserApp.savecheckout'),
        ),
        migrations.AddField(
            model_name='savecheckout',
            name='order_type',
            field=models.CharField(default='Instant', max_length=50),
        ),
        migrations.AddField(
            model_name='savecheckout',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.DeleteModel(
            name='PreBook',
        ),
    ]
