# Generated by Django 6.0.2 on 2026-02-28 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0014_rename_createdat_savecheckout_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiningBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('date_time', models.DateTimeField()),
                ('no_of_people', models.IntegerField()),
                ('special_request', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Confirmed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
