# Generated by Django 6.0.2 on 2026-03-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0015_diningbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diningbooking',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
