# Generated by Django 6.0.2 on 2026-03-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0016_alter_diningbooking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diningbooking',
            name='no_of_people',
        ),
        migrations.AddField(
            model_name='diningbooking',
            name='table_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diningbooking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
