# Generated by Django 6.0.2 on 2026-03-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0017_remove_diningbooking_no_of_people_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diningbooking',
            name='people',
            field=models.IntegerField(default=1),
        ),
    ]
